
library(openxlsx)
library(lubridate)

# Data is available under: https://doi.org/10.7910/DVN/HYP74O

# Terms of use:
# Waiver:
# Our Community Norms as well as good scientific practices expect that proper credit is given via citation. Please use the data citation above, generated by the Dataverse.
# CC0 - "Public Domain Dedication"


# Realizations
SF.rlzC1 <- read.delim2(paste0("data-raw/data_SolarFlares/realizations/FFC3_eventlists_FD_C10min_Z00max_lat00hr_val24hr_since19960731.txt"), sep = "," ,header = FALSE, col.names=c("Date","rlz.C1"), stringsAsFactors=FALSE)
SF.rlzC1$Date <- as.Date(SF.rlz$Date, "%Y.%m.%d")
SF.rlzM1 <- read.delim2(paste0("data-raw/data_SolarFlares/realizations/FFC3_eventlists_FD_M10min_Z00max_lat00hr_val24hr_since19960731.txt"), sep = "," ,header = FALSE, col.names=c("Date","rlz.M1"), stringsAsFactors=FALSE)
SF.rlzM1$Date <- as.Date(SF.rlz$Date, "%Y.%m.%d")

SF.rlz <- merge(SF.rlzM1, SF.rlzC1)


# Predictions
FC.list <- c("AMOS", "ASAP", "ASSA", "BOM", "CLIM120", "DAFFS", "GDAFFS", "MAG4VW", "MAG4VWF", "MAG4W", "MAG4WF", "MCEVOL", "MCSTAT", "MOSWOC", "NICT", "NJIT", "NOAA", "SIDC")
SF.FC.C1 <- NA
SF.FC.M1 <- NA

for (i in 1:length(FC.list)){
  FC.name <- FC.list[i]
  load(paste0("data-raw/data_SolarFlares/predictions/",FC.name,"_release.RData"))

  # formatting
  if (FC.name == "ASSA"){
    x$VALID_DATE <- SF.FC.C1$VALID_DATE
  } else if (FC.name %in% c("CLIM120")){
    x$VALID_DATE <- as.Date(as.character(x$VALID_DATE), "%Y.%m.%d")
  }

  if (i==1){
    SF.FC.C1 <- x[c("VALID_DATE","C1..0.24hr.")]
    SF.FC.M1 <- x[c("VALID_DATE","M1..0.24hr.")]
  } else {
    SF.FC.C1 <- merge(SF.FC.C1, x[c("VALID_DATE","C1..0.24hr.")], by="VALID_DATE")
    SF.FC.M1 <- merge(SF.FC.M1, x[c("VALID_DATE","M1..0.24hr.")], by="VALID_DATE")
  }

  colnames(SF.FC.C1)[i+1] <- FC.list[i]
  colnames(SF.FC.M1)[i+1] <- FC.list[i]
}

# replace the -1 values with NA
SF.FC.C1[(SF.FC.C1 == -1)] <- NA
SF.FC.M1[(SF.FC.M1 == -1)] <- NA

SF.FC.M1 <- merge(SF.FC.M1, SF.rlzM1, by.x="VALID_DATE", by.y="Date")
SF.FC.C1 <- merge(SF.FC.C1, SF.rlzC1, by.x="VALID_DATE", by.y="Date")

# save files as RData
usethis::use_data(SF.FC.C1, overwrite = TRUE)
usethis::use_data(SF.FC.M1, overwrite = TRUE)


