
## ------------------------------------------------------------------------
# Obtain the statistical learning results from Bansak (2019, Political Analysis)
# Source: https://doi.org/10.7910/DVN/KT20FE

# Terms of use:
# Waiver:
# Our Community Norms as well as good scientific practices expect that proper credit is given via citation. Please use the data citation above, generated by the Dataverse.
# CC0 - "Public Domain Dedication"


randomness_setting <- "boot"
crime_charge_processing <- "default"
mturk_setting <- NULL  # NULL is for MTurkers not presented with race
race_subset <- "all"

# -- The following code is taken (and adapted) from the replication material of Bansak (2018) given under https://doi.org/10.7910/DVN/KT20FE

# Load and merge to the original data
br <- read.csv("data-raw/data_recid/data_Bansak/replication_materials/data/BROWARD_CLEAN.csv")

# GBM data
load("data-raw/data_recid/gbm_sim_holding_full.Rdata")
all.ids.predprobs <- out.list$all.ids.predprobs
ntrees.used <- out.list$ntrees.used
depths.used <- out.list$depths.used
br_merge1 <- merge(all.ids.predprobs[[1]], br,
                   by.x = "test.units", by.y = "id",
                   sort = F)

# Logit data
load("data-raw/data_recid/logit_sim_holding_full.Rdata")
all.ids.predprobs <- out.list$all.ids.predprobs
dat_full <- merge(all.ids.predprobs[[1]], br_merge1,
                  by = "test.units",
                  sort = F)


# MTurk
mt <- read.csv("data-raw/data_recid/MTURK_NO_RACE.csv")

mt <- as.matrix(mt)
row.names(mt) <- mt[,1]
#remove first column (Mturker ids):
mt <- mt[,-1]
#convert -1s to 0s:
mt[mt==-1] <- 0

#across mturkers:
mt.correct <- colMeans(mt,na.rm = T)
mean(mt.correct)
median(mt.correct)

#across defendants:
propcorrect <- rowMeans(mt,na.rm = T)
outdat <- data.frame(id = names(propcorrect),propcorrect = propcorrect)
adat <- merge(outdat,br,
              by="id",sort=F)
#convert proportion correct to predicted probability
adat$mturkpredprobs <- ifelse(adat$two_year_recid == 1,
                              adat$propcorrect,
                              1 - adat$propcorrect)


dat_full <- merge(x=dat_full, y=adat[,c("id", "mturkpredprobs")], by.x="test.units", by.y="id")
# Round probability forecasts to 5 digits
dat_full$mturkpredprobs <- round(dat_full$mturkpredprobs,5)


## Compas Data  ------------------------------------------------------------------------
dat_full$compaspredprobs.linear <- (dat_full$compas_decile_score-0.5)/10
recid <- dat_full

# save file as RData
usethis::use_data(recid,overwrite = TRUE)



